#!/bin/bash

#
# useful aliases and functions
# sourced in in .bashrc

#
# aliases
#
alias h="fc -l"
alias e="emacs -nw"
alias ec="emacsclient -nw" 
alias l=more
alias path='echo -e ${PATH//:/\\n}'
alias root="su -"
alias nt="netstat | grep $(hostname) | sort | more"
alias rot13="tr '[A-Za-z]' '[N-ZA-Mn-za-m]'"
alias xterm="xterm -fg white -bg darkslateblue -T xterm\@$(uname -n)"
alias dc3="/usr/bin/dc -e 3k - "
alias macem='/Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs'

#
# and functions
#
function la { ls -haF ${@} ; }
function ll {
    if [ "$INSIDE_EMACS" != "" ]; then
        #
        # no pager in emacs
        ls -hlF ${@}
    else
        ls -hlF ${@} | more
    fi
}
function lla {
    if [ "$INSIDE_EMACS" != "" ]; then
        #
        # no pager in emacs
        ls -hlaF ${@}
    else
        ls -hlaF ${@} | more
    fi
}
function isit { ps -ef | grep ${@} | grep -v grep ; }

function p { ${@} | more ; }

#
# attach to a running tmux, or run a new instance
function tm {
    if [ `tmux ls | wc -l` = "0" ];  then
        tmux
    else
        tmux attach-session
    fi
}


#
# sets precision on dc
function dc { 
    /usr/bin/dc -e 3k - 
}

function setserv {
    if [[ ${#} -gt 1 ]];  then
        echo "\nUsage:"
        echo "       setserv {COMSERV|SYBDEV|SYBTEST}\n"
    else
        DSLISTEN=${@:-DEVSERV}
        DSQUERY=${@:-DEVSERV}
        export DSLISTEN
        export DSQUERY
    fi
    echo "\nCurrent:"
    echo "        DSLISTEN = $DSLISTEN"
    echo "        DSQUERY = $DSQUERY\n"
}


#########################################
# ssh-agent configuration for windows linux subsystem (WSL) and Ubuntu server
# regular linux (X, Gnome, etc.) and macos do this automatically
#########################################
function sshsetup {
    case `uname -v` in
        *Microsoft*|*Ubuntu*)
            if [ -z "$(pgrep ssh-agent)" ]; then
                rm -rf /tmp/ssh-*
                eval $(ssh-agent -s) > /dev/null
            else
                export SSH_AGENT_PID=$(pgrep ssh-agent)
                export SSH_AUTH_SOCK=$(find /tmp/ssh-* -name agent.*)
            fi
            
            if [ "$(ssh-add -l)" == "The agent has no identities." ]; then
                read -p 'Run ssh-add? (N,y) ' addkeys
                # ${foo,,} converts to lowercase
                if [ "${addkeys,,}" == "y" ]; then
                    ssh-add
                fi
            fi
            ;;
        *)
            if [ -z "$(pgrep ssh-agent)" ]; then
                echo "ssh-agent is not running"
            else
                echo "SSH_AGENT_PID=$(pgrep ssh-agent)"
            fi
            ;;
    esac
}


#
# --- eof ---
#
